# usage: use the vscode REST CLIENT plugin to easily run these requests

# get the outputs in the database in a list of dicts
GET http://127.0.0.1:8543/get-outputs HTTP/1.1

###

# add an output to the database
POST http://127.0.0.1:8543/add-outputs HTTP/1.1
content-type: application/json

{
  "output_path": "C:\\users\\docs\\output.xml",
  "output_tags": [
    "tag1",
    "cool-tag2",
    "production_tag"
  ]
}

###

# remove some outputs from the database
DELETE http://127.0.0.1:8543/remove-outputs HTTP/1.1
content-type: application/json

{
  "runs": [
    "0",
    "-1",
    "2025-03-13 00:22:22.304104"
  ]
}
